### ISSUE TITLE
Allow injection on Project Setup Page

### ISSUE THREAD

**Issue by jangari** [grezniczek/redcap_javascript_injector#14]
[This question](https://redcap.vumc.org/community/post.php?id=242611) on community made me think this would be possible by simply redirecting the user to a specific URL (such as the specific dashboard) if the referrer is _not_ a page from within the project, and the current page is either the project home page, or the project setup page.

I have tested this and I can get the behaviour I want for production projects, because I can inject the redirect on the project home page, as that's one of the context that the injector allows for, but since dev projects land on the project setup page, this breaks.

Either I could inject on all pages and then test for the path in window.location.href, which wouldn't be too bad, or otherwise the injector could also be applied to the psp context.

From the look of things it doesn't look like too much of a hassle to implement? But I can't fully get my head around the code, so feel free to let me know if this is more complex than I assumed.

**Comment by grezniczek** [comment]
@jangari - It's rather easy. See this commit: https://github.com/grezniczek/redcap_javascript_injector/commit/b24ae669e9d458bc0918eea89278290e8477436c The code may look (an actually be) a bit complicated because it allows a lot to work by naming stuff a certain way.

New version (https://github.com/grezniczek/redcap_javascript_injector/releases/tag/v2.2.1) should be in the Repo soon.

**Comment by jangari** [comment]
Amazing work! Thank you!
