### ISSUE TITLE
system-level JS injection?

### ISSUE THREAD

**Issue by pbchase** [grezniczek/redcap_javascript_injector#7]
@grezniczek, we have a use case that begs for global JS injection. We want to hide the project completion button and associated text at `./redcap_vX.Y.Z/ProjectSetup/other_functionality.php`. We have the code to do it, but JS Injector only configures at the module level. Any issues with making it configurable at the system level?

You see, we have this cool code just begging to be used. :-)

```javascript
$(document).ready(function() {
    let mark_completion_box = $("table.proj-setup-table:contains('Mark project as Completed')")[0];
    if (mark_completion_box) {
        $(mark_completion_box).hide();
    }
});
```

All credit for the cool code goes to @chemikyle

**Comment by grezniczek** [comment]
@pbchase - Hmm, technically this page _is_ a project page. 

So what you are requesting is a way to always inject certain JS in project-context without having to enable (well, the module **must** be enabled for all projects, otherwise none of the hooks will fire) or to configure some JS in each module.

Because of the _"enabled"_ limitation **this is a bit tricky**, but with some recently added options for admins in module configuration, it should be possible to not blanketly (is tis a word?) expose the JS injector while still enabling it globally. To do so, one would set "Enable module on all projects by default" to **on** while also activating "Hide this module from non-admins in the list of enabled modules on each project" (which can then be overridden in some projects only).   
The drawback of this, however, would be that the module can no longer be _discovered_ by users.

Do you think this is feasible for admins? It is quite a drastic change.



Regarding the cool code ;): Not cool at all, as it works with a hardcoded (English) string that may or may not work depending on the INI file a project is running. A better way to select the table would be: 
```js
$('button[onclick="markProjectAsCompleted();"]').parents('table');
```

There is no need for the `if`. Simply call it direclty on the jQuery result.

Also - do you really want to hide the entire table? This will remove the "Move to Analysis/Cleanup" and other state changing buttons as well.  You probably only want to remove the row.

```js
$('button[onclick="markProjectAsCompleted();"]').parents('tr').hide()
```

And maybe even use `remove()` instead of `hide()`. Reduces the chances of people using F12 to find the "lost" button only to call `markProjectAsCompleted()` in the console. They still might, however, if they know ....

Edit: To address the _hacking issue_ ... the function could be replaced by something like this (probably without the console log and click ;):
```js
window.markProjectAsCompleted = function() { console.log('Nice try!'); $('a[href*="logout=1"]')[0].click(); }
```

**Comment by grezniczek** [comment]
@pbchase - I guess I got sidetracked a bit ... 

The issue that warrants some discussion is that at the top of the previous post and the question is, whehter the proposed solution is feasible. We'd have to document it this way so admins know the price for "system" level functionality.

**Comment by pbchase** [comment]
> I guess I got sidetracked a bit ...

That's my fault for sharing code which Kyle called a hack to which I said I didn't care. :-) I distracted you.

I'll let you and Kyle hack out the merits and demerits of what I have suggested. I doubt I have any objectivity as I am annoyed with my customers and want nothing more than to make the problem go away.

**Comment by ChemiKyle** [comment]
> Regarding the cool code ;): Not cool at all, as it works with a hardcoded (English) string that may or may not work depending on the INI file a project is running.

I made this _exact_ argument just about verbatim, so thank you for echoing my own complaint about the hack that I wrote during a meeting! I do not want credit for this very uncool code that I wrote in about 10 minutes.  
However, the actual useful thing we want is indeed system-level JS injection.

**Comment by pbchase** [comment]
I work under the philosophy that if you do a sufficiently poor job eventually you will be relieved of it, but somehow Kyle still lets me post public issues on Github. ;-)

**Comment by grezniczek** [comment]
Haha. The danger of these work ethics are that they might backfire someday ...

https://github.com/grezniczek/redcap_javascript_injector/tree/system-injection has some additions to the configuration and updates to the docs. Nothing functional yet, but I'd appreciated **feedback** on how the configuration will work (see `config.json` or install this branch in a test instance).

I am thinking of using the many checkboxes/dropdowns approach for project config, too.

**Comment by grezniczek** [comment]
@pbchase @ChemiKyle - Here it is, the shine new [JS Injector](https://github.com/grezniczek/redcap_javascript_injector/releases/tag/v2.0.0beta1) that supports SYSTEM LEVEL injection, as requested.

Be aware though that the EM framework will **not** trigger any hooks in projects where the module is not enabled. Thus, it is impossible to satisfy your use case _unless_ the JS Injector EM is enabled for all projects (see [above](https://github.com/grezniczek/redcap_javascript_injector/issues/7#issuecomment-1402269149) and in the [README](https://github.com/grezniczek/redcap_javascript_injector/tree/v2.0.0beta1)).

**Please do test** the v2.0.0 beta release, and especially check if the automatic conversion of module configuration to the new model employed by v2 succeeds. Be aware that there is no going back after the conversion happend (which is when the new version is enabled). Obviously, do not test this on a production instance!

I'll do some more testing myself, but it would be great to have some outside feedback before I push this to the Repository.

https://github.com/grezniczek/redcap_javascript_injector/releases/tag/v2.0.0beta1
